### ISSUE TITLE
Delete method is getting me a error.

### ISSUE THREAD

**Issue by sergiosusa** [Api2Pdf/api2pdf.php#10]
Hi, 

We are starting to use your api but i get an error when i delete a generated pdf: 

Looks like there is no pdf file on data when you try to create de ApiResponse object whitch is correct, file already delete.

` '{
  "mbIn": 0.0,
  "mbOut": 0.0,
  "cost": 6.4011E-05,
  "success": true,
  "error": null,
  "responseId": "46b3ab82-aaa2-4103-a856-5ea5b515962e"
}' `

i'm going to let a PR to fixed up.

**Comment by apexdodge** [comment]
Pull request was accepted
