### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by fillmore-admin** [Api2Pdf/api2pdf.php#12]
PHP Fatal error:  Uncaught Api2Pdf\Exception\ProtocolException: SSL certificate problem: unable to get local issuer certificate in vendor\api2pdf\api2pdf.php\src\Api2Pdf.php:128

Do you have a support page on what I'm missing here? My server does use an SSL cert, I'm not sure what my next step is.

**Comment by apexdodge** [comment]
Hello, this stackoverflow post is relevant to you: https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

Couple options:

1) You could fork the repository and modify the code to add this line to make unsecure connections: 

![image](https://user-images.githubusercontent.com/777005/64740863-b3fea780-d4c4-11e9-9815-109fb7a9d52b.png)

2) You could follow the other recommendations about adding the certificates to your server

3) You don't need to use the php library. You can write your own PHP code that does unsecure connections by following the rest API here: https://www.api2pdf.com/documentation

Thanks

**Comment by fillmore-admin** [comment]
I do have an SSL certificate, how do I make a secure request?


Justin James
App Developer & IT Coordinator

Fillmore Construction Management Inc.
Desk: 780-638-1008 | Cell: 780-235-6035
9114 34A Avenue, Edmonton, Alberta, T6E 5P4
Email: jjames@fcmi.net<mailto:jjames@fcmi.net> | www.fillmoreconstruction.com<http://www.fillmoreconstruction.com/>


[cid:image021.jpg@01D3AFEF.6A24FD90]    [cid:image022.png@01D3AFEF.6A24FD90]
[http://bfapps1.boundlessfundraising.com/badge/bikemsca/display/2965437/6515/status.jpg]<http://mssoc.convio.net/goto/justinjjames>

On Sep 11, 2019, at 4:49 PM, Zack Schwartz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, this stackoverflow post is relevant to you: https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

Couple options:

  1.  You could fork the repository and modify the code to add this line to make unsecure connections:

[image]<https://user-images.githubusercontent.com/777005/64740863-b3fea780-d4c4-11e9-9815-109fb7a9d52b.png>

  1.  You could follow the other recommendations about adding the certificates to your server

  2.  You don't need to use the php library. You can write your own PHP code that does unsecure connections by following the rest API here: https://www.api2pdf.com/documentation

Thanks

**Comment by apexdodge** [comment]
You have to see option 2 and the guidance offered in the responses in that stackoverflow post here: https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

It's likely some configuration issue in your server that you have to resolve. Not something we have expertise in so we can't provide further guidance.

**Comment by fillmore-admin** [comment]
> You have to see option 2 and the guidance offered in the responses in that stackoverflow post here: https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate
> 
> It's likely some configuration issue in your server that you have to resolve. Not something we have expertise in so we can't provide further guidance.

Sorry my bad, I see the link is for getting the SSL/https working. Thank you for your help!
