### ISSUE TITLE
PHP Fatal error:  Class 'Api2Pdf\Exception\ConversionException' not found

### ISSUE THREAD

**Issue by faizahfaiqahAS** [Api2Pdf/api2pdf.php#16]
Hi. Im new to Api2Pdf. Im using this for merging bunch of files to create a pdf document. Currently im facing an issue: 

PHP Fatal error:  Class 'Api2Pdf\Exception\ConversionException' not found in /api2pdf/src/ApiResult.php on line 52

From the beginning, I never do any changes in Api2Pdf source codes. I just call merge functions. Is it possible that this happens because of the merging process is too heavy because i compile too many pdfs?

**Comment by apexdodge** [comment]
The error:

> PHP Fatal error: Class 'Api2Pdf\Exception\ConversionException' not found in /api2pdf/src/ApiResult.php on line 52

You may not have setup your php and copied over the files correctly. Without that, next best thing you can do is login to the portal at portal.api2pdf.com and look at your request log and it might show the error there.

Beyond that, there is not enough information here to provide further guidance.
