### ISSUE TITLE
Documentation says Headless Chrome paperWidth and paperHeight default to 8.5in by 11in., but it's defaulting to A4 size

### ISSUE THREAD

**Issue by gavin310** [Api2Pdf/api2pdf.php#17]
In the API2PDF docs (https://www.api2pdf.com/documentation/advanced-options-headless-chrome/) it says `paperWidth` and `paperHeight` default to 8.5in by 11in respectively. In my CSS I have:

```
@page {
	size: letter;
	margin: 0;
}
```

I wasn't passing any options to the API. After struggling for hours to figure out where this extra "margin" was coming from. I screenshotted the PDF and measured it and figured out it was A4 size. So I set `paperWidth` to `8.5` and paperHeight to `11` and the page size was correct.

Are the docs wrong? Why was my page size defaulting to A4?

**Comment by apexdodge** [comment]
Looks like the documentation was off. I've corrected them now to 8.27in / 11.69in to reflect the A4 defaults. Thanks for the report.
