### ISSUE TITLE
wrong notation in documentation

### ISSUE THREAD

**Issue by Ymx1ZQ** [Api2Pdf/api2pdf.php#2]
in PHP, methods are not noted with a dot, but with an arrow:

`$api_response = $a2p_client.wkhtmltopdf_from_html('<p>Hello, World</p>');`
is wrong

`$api_response = $a2p_client->wkhtmltopdf_from_html('<p>Hello, World</p>');`
is correct

**Comment by apexdodge** [comment]
Updated, thanks
