### ISSUE TITLE
Dependencies Aura/Intl not installable with PHP8

### ISSUE THREAD

**Issue by routingsystems** [Api2Pdf/api2pdf.php#21]
Aura/Intl is not compatible with PHP8 and the project seems no active anymore. 
Any solution to resolve it ?

**Comment by apexdodge** [comment]
v2 is almost ready and the library was rewritten. Can preview it here: https://github.com/Api2Pdf/api2pdf.php/tree/2.0.0

I don't see any dependency on aura/intl so this should be a non issue with php 8. If there are still issues please re-open.
