### ISSUE TITLE
enable psr-4 / composer

### ISSUE THREAD

**Issue by Ymx1ZQ** [Api2Pdf/api2pdf.php#4]
would it be possible to provide a composer installation method compliant with psr-4?
https://getcomposer.org/doc/04-schema.md

of course copying the file (with some little customization) works... but it would be far preferable to have the possibility of installing this library through the composer

**Comment by apexdodge** [comment]
Yes, this is definitely the goal. My expertise is in Python and C# so I need to do more research in this.

**Comment by Ymx1ZQ** [comment]
Adding a package to the composer repositories is pretty straightforward! I
would suggest that you simply follow the instructions at
https://packagist.org and https://packagist.org/about ! Packagist is the
main composer repository!

**Comment by arkamax2k** [comment]
@apexdodge , check out https://github.com/Api2Pdf/api2pdf.php/pull/5 - this should get it where it needs to be for (at least partial) PSR compliance and Composer compatibility.

**Comment by apexdodge** [comment]
Thank you, I will review
